### ISSUE TITLE
Use Dependabot to keep dependencies up to date

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-secret-buddy#16]
This repo has two types of dependencies:
1. Go dependencies (in `go.mod`)
2. The GitHub Actions such as `actions/checkout` and `actions/setup-go` in the CI workflow file

GitHub's Dependabot tool is able to keep both up to date - and for bonus points they have recently added support for "grouped updates" which can reduce the noise of Dependabot PRs.

A Dependabot config something like this should work:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      go-dependencies:
        update-types:
          - "minor"
          - "patch"
```

(In our team's repos, we don't tend to bother enabling grouping for the "github-actions" updates, since they are much less frequent)

For more information, see:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
